services:
  meu-postgres:
    image: postgres:15-alpine
    container_name: container-postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER_ROOT}
      - POSTGRES_PASSWORD=${POSTGRES_PASS_ROOT}
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
